services:
  app:
    image: timely-tasks:latest
    container_name: timely-tasks-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5010:3000"
