name: Build and push Docker image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: actor_lc
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.actor }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.actor_lc.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to multiple registries
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/app:latest
            ghcr.io/${{ steps.actor_lc.outputs.lowercase }}/app:latest
          vars: |
            DOCS_SERVER_URL=${{ vars.DOCS_SERVER_URL }}
